import type { TOption } from "@bellaclaw/shared";
import { RRule } from "rrule";
import type { TEventDateTime } from "./types";

export type TRecurrenceSplit = {
  original: string[];
  successor: string[];
};

function wallClockDate(value: string, timezone: TEventDateTime["timeZone"]): Date {
  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return new Date(`${value}T00:00:00Z`);
  }
  const instant = new Date(value);
  if (timezone === undefined) {
    return instant;
  }
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: timezone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hourCycle: "h23",
  }).formatToParts(instant);
  const part = (type: Intl.DateTimeFormatPartTypes): number =>
    Number(parts.find((candidate) => candidate.type === type)?.value);
  return new Date(
    Date.UTC(
      part("year"),
      part("month") - 1,
      part("day"),
      part("hour"),
      part("minute"),
      part("second"),
    ),
  );
}

export function countRuleOccurrencesBefore(
  recurrence: string[],
  start: TEventDateTime,
  boundary: TEventDateTime,
): number {
  const ruleLine = recurrence.find((line) => line.startsWith("RRULE:"));
  const startValue = start.dateTime ?? start.date;
  const boundaryValue = boundary.dateTime ?? boundary.date;
  if (ruleLine === undefined || startValue === undefined || boundaryValue === undefined) {
    throw new Error("COUNT recurrence boundary cannot be resolved");
  }
  const options = RRule.parseString(ruleLine.slice(6));
  const startDate = wallClockDate(startValue, start.timeZone);
  const boundaryDate = wallClockDate(boundaryValue, start.timeZone);
  options.dtstart = startDate;
  const rule = new RRule(options);
  return rule.between(new Date(startDate.getTime() - 1), boundaryDate, false).length;
}

function assertBoundaryGeneratedByEveryRule(
  recurrence: string[],
  start: TEventDateTime,
  boundary: TEventDateTime,
): void {
  const startValue = start.dateTime ?? start.date;
  const boundaryValue = boundary.dateTime ?? boundary.date;
  if (startValue === undefined || boundaryValue === undefined) {
    throw new Error("Recurring occurrence boundary cannot be resolved");
  }
  const startDate = wallClockDate(startValue, start.timeZone);
  const boundaryDate = wallClockDate(boundaryValue, start.timeZone);
  for (const line of recurrence) {
    if (!line.startsWith("RRULE:")) {
      continue;
    }
    const options = RRule.parseString(line.slice(6));
    options.dtstart = startDate;
    const generated = new RRule(options).after(boundaryDate, true);
    if (generated === null || generated.getTime() !== boundaryDate.getTime()) {
      throw new Error("Following scope boundary is not generated by every RRULE");
    }
  }
}

function recurrenceTimestamp(value: string): number {
  const normalized = value
    .replace(/^TZID=[^:]+:/, "")
    .replace(/^VALUE=DATE:/, "")
    .replace(/^.*:/, "");
  if (/^\d{8}$/.test(normalized)) {
    return Date.parse(
      `${normalized.slice(0, 4)}-${normalized.slice(4, 6)}-${normalized.slice(6, 8)}T00:00:00Z`,
    );
  }
  if (/^\d{8}T\d{6}Z$/.test(normalized)) {
    return Date.parse(
      `${normalized.slice(0, 4)}-${normalized.slice(4, 6)}-${normalized.slice(6, 8)}T${normalized.slice(9, 11)}:${normalized.slice(11, 13)}:${normalized.slice(13, 15)}Z`,
    );
  }
  return Number.NaN;
}

function localBoundaryOrder(boundary: number, timezone: string): number {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: timezone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hourCycle: "h23",
  }).formatToParts(new Date(boundary));
  let compact = "";
  for (const type of ["year", "month", "day", "hour", "minute", "second"]) {
    compact += parts.find((part) => part.type === type)?.value ?? "";
  }
  return Number(compact);
}

function formatUntil(boundary: number, allDay: boolean): string {
  const before = new Date(boundary - 1_000);
  const compact = before.toISOString().replaceAll("-", "").replaceAll(":", "").replace(".000", "");
  if (allDay) {
    return compact.slice(0, 8);
  }
  return compact;
}

function partitionValues(
  line: string,
  boundary: number,
): { original: TOption<string>; successor: TOption<string> } {
  const separator = line.indexOf(":");
  if (separator === -1) {
    return { original: line, successor: line };
  }
  const prefix = line.slice(0, separator + 1);
  const timezone = line.match(/TZID=([^:;]+)/)?.[1];
  let localBoundary = boundary;
  if (timezone !== undefined) {
    localBoundary = localBoundaryOrder(boundary, timezone);
  }
  const before: string[] = [];
  const after: string[] = [];
  for (const value of line.slice(separator + 1).split(",")) {
    let timestamp = recurrenceTimestamp(value);
    if (timezone !== undefined) {
      if (Number.isNaN(timestamp)) {
        timestamp = Number(value.replace(/\D/g, ""));
      } else {
        timestamp = localBoundaryOrder(timestamp, timezone);
      }
    }
    if (!Number.isNaN(timestamp) && timestamp >= localBoundary) {
      after.push(value);
    } else {
      before.push(value);
    }
  }
  let original: TOption<string>;
  if (before.length > 0) {
    original = `${prefix}${before.join(",")}`;
  }
  let successor: TOption<string>;
  if (after.length > 0) {
    successor = `${prefix}${after.join(",")}`;
  }
  return { original, successor };
}

export function splitRecurrence(
  recurrence: string[],
  start: TEventDateTime,
  boundary: TEventDateTime,
  occurrenceNumbers?: number[],
): TRecurrenceSplit {
  assertBoundaryGeneratedByEveryRule(recurrence, start, boundary);
  const boundaryValue = boundary.dateTime ?? boundary.date;
  if (boundaryValue === undefined) {
    throw new Error("Recurring occurrence has no original start time");
  }
  const boundaryTimestamp = Date.parse(boundaryValue);
  if (Number.isNaN(boundaryTimestamp)) {
    throw new Error("Recurring occurrence has an invalid original start time");
  }

  const original: string[] = [];
  const successor: string[] = [];
  let countRuleIndex = 0;
  for (const line of recurrence) {
    if (line.startsWith("RRULE:")) {
      const parts = line.slice(6).split(";");
      const preserved = parts.filter(
        (part) => !part.startsWith("COUNT=") && !part.startsWith("UNTIL="),
      );
      const countPart = parts.find((part) => part.startsWith("COUNT="));
      if (countPart !== undefined) {
        const occurrenceNumber = occurrenceNumbers?.[countRuleIndex];
        countRuleIndex += 1;
        if (occurrenceNumber === undefined || occurrenceNumber < 1) {
          throw new Error("COUNT recurrence requires a resolved occurrence number");
        }
        const count = Number(countPart.slice(6));
        if (!Number.isInteger(count) || occurrenceNumber >= count) {
          throw new Error("COUNT recurrence cannot be split at this occurrence");
        }
        original.push(`RRULE:${[...preserved, `COUNT=${occurrenceNumber}`].join(";")}`);
        successor.push(`RRULE:${[...preserved, `COUNT=${count - occurrenceNumber}`].join(";")}`);
        continue;
      }
      original.push(
        `RRULE:${[...preserved, `UNTIL=${formatUntil(boundaryTimestamp, boundary.date !== undefined)}`].join(";")}`,
      );
      const untilPart = parts.find((part) => part.startsWith("UNTIL="));
      if (untilPart !== undefined) {
        successor.push(`RRULE:${[...preserved, untilPart].join(";")}`);
      } else {
        successor.push(`RRULE:${preserved.join(";")}`);
      }
      continue;
    }
    if (line.startsWith("RDATE") || line.startsWith("EXDATE")) {
      const values = partitionValues(line, boundaryTimestamp);
      if (values.original !== undefined) {
        original.push(values.original);
      }
      if (values.successor !== undefined) {
        successor.push(values.successor);
      }
      continue;
    }
    original.push(line);
    successor.push(line);
  }
  return { original, successor };
}
