import { describe, expect, test } from "bun:test";
import { countRuleOccurrencesBefore, splitRecurrence } from "./recurrence";

describe("recurrence splitting", () => {
  test("partitions COUNT and exception dates", () => {
    const split = splitRecurrence(
      [
        "RRULE:FREQ=DAILY;COUNT=10",
        "RDATE:20260726T090000Z,20260730T090000Z",
        "EXDATE:20260727T090000Z,20260731T090000Z",
      ],
      { date: undefined, dateTime: "2026-07-25T09:00:00Z", timeZone: "UTC" },
      { date: undefined, dateTime: "2026-07-29T09:00:00Z", timeZone: "UTC" },
      [4],
    );

    expect(split.original).toEqual([
      "RRULE:FREQ=DAILY;COUNT=4",
      "RDATE:20260726T090000Z",
      "EXDATE:20260727T090000Z",
    ]);
    expect(split.successor).toEqual([
      "RRULE:FREQ=DAILY;COUNT=6",
      "RDATE:20260730T090000Z",
      "EXDATE:20260731T090000Z",
    ]);
  });

  test("compares TZID recurrence values in the same wall-clock representation", () => {
    const split = splitRecurrence(
      ["RRULE:FREQ=DAILY;COUNT=10", "RDATE;TZID=Europe/Warsaw:20260725T063000Z,20260725T073000Z"],
      {
        date: undefined,
        dateTime: "2026-07-24T09:00:00+02:00",
        timeZone: "Europe/Warsaw",
      },
      {
        date: undefined,
        dateTime: "2026-07-25T09:00:00+02:00",
        timeZone: "Europe/Warsaw",
      },
      [1],
    );

    expect(split.original).toContain("RDATE;TZID=Europe/Warsaw:20260725T063000Z");
    expect(split.successor).toContain("RDATE;TZID=Europe/Warsaw:20260725T073000Z");
  });

  test("preserves the original UNTIL on the successor", () => {
    const split = splitRecurrence(
      ["RRULE:FREQ=WEEKLY;UNTIL=20261201T100000Z"],
      { date: undefined, dateTime: "2026-08-25T10:00:00Z", timeZone: "UTC" },
      {
        date: undefined,
        dateTime: "2026-09-01T10:00:00Z",
        timeZone: "UTC",
      },
    );

    expect(split.original[0]).toContain("UNTIL=20260901T095959Z");
    expect(split.successor[0]).toContain("UNTIL=20261201T100000Z");
  });

  test("counts only RRULE positions before moved, RDATE, and EXDATE exceptions", () => {
    expect(
      countRuleOccurrencesBefore(
        ["RRULE:FREQ=DAILY;COUNT=10", "RDATE:20260724T120000Z", "EXDATE:20260726T090000Z"],
        { date: undefined, dateTime: "2026-07-24T09:00:00Z", timeZone: "UTC" },
        { date: undefined, dateTime: "2026-07-28T09:00:00Z", timeZone: "UTC" },
      ),
    ).toBe(4);
  });

  test("reports zero positions before the first occurrence", () => {
    expect(
      countRuleOccurrencesBefore(
        ["RRULE:FREQ=DAILY;COUNT=10"],
        { date: undefined, dateTime: "2026-07-24T09:00:00Z", timeZone: "UTC" },
        { date: undefined, dateTime: "2026-07-24T09:00:00Z", timeZone: "UTC" },
      ),
    ).toBe(0);
  });

  test("counts wall-clock positions correctly across Warsaw DST fallback", () => {
    expect(
      countRuleOccurrencesBefore(
        ["RRULE:FREQ=DAILY;COUNT=10"],
        {
          date: undefined,
          dateTime: "2026-10-23T09:00:00+02:00",
          timeZone: "Europe/Warsaw",
        },
        {
          date: undefined,
          dateTime: "2026-10-27T09:00:00+01:00",
          timeZone: "Europe/Warsaw",
        },
      ),
    ).toBe(4);
  });

  test("splits each COUNT rule at its own position", () => {
    const split = splitRecurrence(
      ["RRULE:FREQ=DAILY;COUNT=10", "RRULE:FREQ=WEEKLY;BYDAY=WE;COUNT=8"],
      { date: undefined, dateTime: "2026-07-25T09:00:00Z", timeZone: "UTC" },
      { date: undefined, dateTime: "2026-07-29T09:00:00Z", timeZone: "UTC" },
      [4, 1],
    );

    expect(split.original).toEqual([
      "RRULE:FREQ=DAILY;COUNT=4",
      "RRULE:FREQ=WEEKLY;BYDAY=WE;COUNT=1",
    ]);
    expect(split.successor).toEqual([
      "RRULE:FREQ=DAILY;COUNT=6",
      "RRULE:FREQ=WEEKLY;BYDAY=WE;COUNT=7",
    ]);
  });

  test("rejects a boundary not generated by every copied RRULE", () => {
    expect(() =>
      splitRecurrence(
        ["RRULE:FREQ=DAILY;COUNT=10", "RRULE:FREQ=WEEKLY;BYDAY=FR;COUNT=8"],
        { date: undefined, dateTime: "2026-07-24T09:00:00Z", timeZone: "UTC" },
        { date: undefined, dateTime: "2026-07-29T09:00:00Z", timeZone: "UTC" },
        [5, 1],
      ),
    ).toThrow("not generated by every RRULE");
  });

  test("rejects an RDATE-only split boundary", () => {
    expect(() =>
      splitRecurrence(
        ["RRULE:FREQ=WEEKLY;BYDAY=FR;COUNT=8", "RDATE:20260729T090000Z"],
        { date: undefined, dateTime: "2026-07-24T09:00:00Z", timeZone: "UTC" },
        { date: undefined, dateTime: "2026-07-29T09:00:00Z", timeZone: "UTC" },
        [1],
      ),
    ).toThrow("not generated by every RRULE");
  });
});
