import type { ToolDefinitionJson } from "@openrouter/sdk/models";

export const SCHEDULE_ONCE_TOOL = "schedule-once" as const;

export const scheduleOnceTool: ToolDefinitionJson = {
  type: "function",
  function: {
    name: SCHEDULE_ONCE_TOOL,
    description:
      "Schedule a one-time reminder that fires once at a specific future date and time, then removes itself.",
    parameters: {
      type: "object",
      properties: {
        name: {
          type: "string",
          description:
            "A unique identifier for this one-time job. Used to reference the job when unscheduling or updating.",
        },
        fireAt: {
          type: "string",
          description:
            "The exact future date and time when the reminder should fire. Use an ISO 8601 timestamp with timezone offset when possible.",
        },
        group: {
          type: "string",
          description: "Optional group label stored with the cron job.",
        },
        reminderText: {
          type: "string",
          description:
            "Plain text reminder content to send when the job fires. Provide this for direct, non-generated reminders.",
        },
        reminderPromptData: {
          type: "string",
          description:
            "Structured prompt data serialized as a JSON string to regenerate the reminder message later in a tool loop. Provide this instead of reminderText when the reminder should be generated by the LLM.",
        },
        reminderFallbackText: {
          type: "string",
          description:
            "Fallback reminder text to send if regeneration is unavailable or fails. Required when reminderPromptData is set.",
        },
        overwrite: {
          type: "boolean",
          description:
            "If true, replace an existing one-time job with the same name. Defaults to false.",
        },
      },
      required: ["name", "fireAt"],
      oneOf: [
        {
          not: {
            required: ["reminderPromptData"],
          },
          required: ["reminderText"],
        },
        {
          not: {
            required: ["reminderText"],
          },
          required: ["reminderPromptData", "reminderFallbackText"],
        },
      ],
    },
  },
};
